version: "3.8"

services:
  db:
    build:
      context: ./infra
      dockerfile: docker/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symbio_db
      POSTGRES_USER: ayush_admin
      POSTGRES_PASSWORD: troy_secure_pass
    volumes:
      - ./infra/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped


  api:
    image: ghcr.io/ayush330/symbio/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ayush_admin
      DB_PASSWORD: troy_secure_pass
      DB_NAME: symbio_db
      JWT_SECRET: supersecretdefaultkey_change_in_prod
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./backend/firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  pgdata:
